---
title: "git_01"
author: "Abel Jacobo Perez"
date: "09-21-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“You are old, Father William,” the young man said,  
“And your hair has become very white;  
And yet you incessantly stand on your head –  
Do you think, at your age, it is right?”  

“In my youth,” Father William replied to his son,  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
   Shining with all his might:  
He did his very best to make  
   The billows smooth and bright—  
And this was odd, because it was  
   The middle of the night.  

The moon was shining sulkily,  
   Because she thought the sun  
Had got no business to be there  
   After the day was done—  
"It's very rude of him," she said,  
   "To come and spoil the fun!"  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
or starve. Too much. Or not enough. Or. Nothing else?  
Nothing else. Too high too fast too organized too invisible.  
Will we survive I ask the bot. No. To download bot be  
swift—you are too backward, too despotic—to load greatly enlarge  
the cycle of labor—to load abhor labor—move to the  
periphery, of your body, your city, your planet—to load, degrade, immiserate,  
be your own deep sleep—to load use your lips—use them  
to mouthe your oath, chew it—do the 
dirty thing, sing it, blown off limb or syllable, lick it back on 
with your mouth—talk—talk—who is not  
